### ISSUE TITLE
sbt run doesn't work as described in the README

### ISSUE THREAD

**Issue by ritschwumm** [frp/raytracing#1]
could you add a minimal build.sbt and project/build.properties ?

**Comment by frp** [comment]
What results do you get when you do "sbt run"?
Theoretically it should work without config at all (and works for me and a few other people).

If actually needed, I'll add build.sbt and project/build.properties when I will get some free time (maybe the next weekend).

**Comment by ritschwumm** [comment]
sorry, my fault - it does indeed work as advertised. my sbt wrapper script is a little bit too smart :(
